### ISSUE TITLE
.class showing as constant.language.js

### ISSUE THREAD

**Issue by laggingreflex** [davidrios/jade-tmbundle#33]
![](http://i.imgur.com/96uiu9q.png)

This is just a class deceleration and its being labled as '`constant.language.js`'

**Comment by davidrios** [comment]
Yeah, this is a workaround to display the class in a different color.

**Comment by kumarharsh** [comment]
That's not a correct thing to do though. You should be contributing to fix the offending theme rather than breaking the language definition file.
