### ISSUE TITLE
Unable to open Packages/jQuery/Syntaxes/jQueryJavaScript.tmLanguage

### ISSUE THREAD

**Issue by laggingreflex** [davidrios/jade-tmbundle#37]
Some of my jade files seem to crash and revert to plain-text

Error is something about jQuery

![](http://i.imgur.com/JGOYP9p.png)

**Comment by karlkeefer** [comment]
The other issue #39 that I just closed appears to be a flavor of this error -> when I restarted sublime it was having a similar error:

![related](https://cloud.githubusercontent.com/assets/305272/5748510/5cf5df9c-9bf5-11e4-9ba3-502c9baaa021.png)

**Comment by laggingreflex** [comment]
I wasn't using ES6 module.

I also think it's some syntax that causes this. I'll check the next time I go back to working with those specific jade files that cause this.

**Comment by davidrios** [comment]
Closing as those problems seem to be caused by external packages.
