### ISSUE TITLE
ternary operator breaks highlighting

### ISSUE THREAD

**Issue by karlkeefer** [davidrios/jade-tmbundle#39]
I've seen this happen with the use of `?` inside of `#{}` blocks as well
![ternary](https://cloud.githubusercontent.com/assets/305272/5746806/3ef4f496-9be7-11e4-8535-1cf956b7f2b6.png)

**Comment by davidrios** [comment]
Are you sure you're using this package and at the latest version? I can't reproduce your error. If so, try disabling all other packages and testing.

**Comment by karlkeefer** [comment]
I'll give that a shot, this wasn't happening before so I assumed it might have come with a new update. I'll run uninstall, reinstall, and try it in isolation to make sure.

**Comment by karlkeefer** [comment]
`"version": "2014.11.17.11.43.28"`

Still shows up ->
![uncommented](https://cloud.githubusercontent.com/assets/305272/5748155/a05873e2-9bf2-11e4-9acd-ea2dfdc3a64a.png)

Commenting out the offending line restores proper highlighting ->
![commented](https://cloud.githubusercontent.com/assets/305272/5748154/a0560008-9bf2-11e4-97db-675bdd17fefc.png)

if I change the line with ternary to ->
`-var addressAction = myVar ? true : false;` the problem goes away

but if the values being assigned are in quotes ->
`-var addressAction = myVar ? 'true' : 'false';` it's back.

Jade (Python) doesn't have the same issue with ternary, but at first glance appears to handle various things differently.

The code from my demo if it helps reproduce ->
````jade
-var addressAction = myVar ? 'true' : 'false';
form(action="#{addressAction}", method="post")
  +stringField('full_name', address)
  +stringField('address_line', address)
  +stringField('city', address)
  +stringField('state', address)
  +stringField('zip', address)
  div.form-group
    label Country
    select.form-control(name="country_id")
```

**Comment by karlkeefer** [comment]
Whoa - hold the phone - something really odd going on with package manager on my setup - I think you're right that this is stemming from some kind conflict between packages.
