### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by PageRankSEO** [davidrios/jade-tmbundle#40]
David,

Hi.

Last night, I attempted to add your jade-tmbundle to Sublime Text 3 by pasting the following lines into the Console:
mkdir -p ~/Library/Application\ Support/Sublime\ Text\ 3/Packages
cd ~/Library/Application\ Support/Sublime\ Text\ 3/Packages
git clone https://github.com/davidrios/jade-tmbundle.git Jade

I receive the following error.
2015-02-06 22:11:32 or after
>>> mkdir -p ~/Library/Application\ Support/Sublime\ Text\ 3/Packages
  File "<string>", line 1
    mkdir -p ~/Library/Application\ Support/Sublime\ Text\ 3/Packages
             ^
SyntaxError: invalid syntax
>>> mkdir -p ~/Library/Application\ Support/Sublime\ Text\ 3/Packages
  File "<string>", line 1
    mkdir -p ~/Library/Application\ Support/Sublime\ Text\ 3/Packages

I also attempted to add jade support with your jade-tmbundle via Terminal.

macpro41s-pro:Bundles Home$ sudo mkdir -p ~/Library/Application\ Support/Sublime\ Text\ 3/Packages
macpro41s-pro:Bundles Home$ sudo cd ~/Library/Application\ Support/Sublime\ Text\ 3/Packages
macpro41s-pro:Bundles Home$ sudo git clone https://github.com/davidrios/jade-tmbundle.git Jade
Cloning into 'Jade'...
remote: Counting objects: 442, done.
remote: Compressing objects: 100% (190/190), done.
remote: Total 442 (delta 236), reused 442 (delta 236)
Receiving objects: 100% (442/442), 91.60 KiB | 0 bytes/s, done.
Resolving deltas: 100% (236/236), done.
Checking connectivity... done.

Although this appears it was successful, installing Jade via Package Control: Install Package is not an option. Upon typing jade into the search field, "Jade" does not appear in the list of found resources.

FYI: Using Terminal and your jade-tmbundle I was successfully able to add Jade to TextMate 2. Jade is now available in the Bundle drop down menu. Thanks.

macpro41s-pro:Bundles Home$ sudo mkdir -p ~/Library/Application\ Support/TextMate/Managed/Bundles
macpro41s-pro:Bundles Home$ sudo cd ~/Library/Application\ Support/TextMate/Managed/Bundles
macpro41s-pro:Bundles Home$ sudo git clone https://github.com/davidrios/jade-tmbundle.git Jade.tmbundle
Cloning into 'Jade.tmbundle'...
remote: Counting objects: 442, done.
remote: Compressing objects: 100% (190/190), done.
remote: Total 442 (delta 236), reused 442 (delta 236)
Receiving objects: 100% (442/442), 91.60 KiB | 0 bytes/s, done.
Resolving deltas: 100% (236/236), done.
Checking connectivity... done.

Wondering if it's a directory issue in Sublime Text 3? The version I have is Sublime Text 3065.

Thanks.

Rob

**Comment by davidrios** [comment]
I can't test if it's a problem on macos, since I use linux, I didn't have any problems here. One thing I was able to test though is that if you have a directory named Jade on the packages folder, then Package Control won't show Jade in the list of installable packages, removing it solves the problem.

**Comment by davidrios** [comment]
Closing as no further feedback was provided.
