### ISSUE TITLE
Support angle brackets

### ISSUE THREAD

**Issue by OnkelTem** [davidrios/jade-tmbundle#42]
Consider this jade example:
```
- var el = 'div'; attrs = 'dir="ltr"'
<!{el} !{attrs}>
| blah
</!{el}>
```
this is how it renders in ST3:
![Screenshot] (https://sc-cdn.scaleengine.net/i/7c6d1e415fd7348f2fba7d4ab65cd26a.png)

**Comment by davidrios** [comment]
That's a weird way of doing that. As far as I know this is the official way of accomplishing what you want:

```jade
- var el = 'div'; var attrs = {'dir': 'ltr'}
#{el}&attributes(attrs) blah
```

**Comment by OnkelTem** [comment]
Thanks for the reply! Wow, I didn't know about ```#{el}``` syntax. Documentation on jade-lang.com seems to be pretty outdated. Which docs are you using?

As for the example, well, this is not the same as I do: in my example attributes are like prerendered, they are of  type string and I'm not sure how to add them in jade. Ideas?

Also, I'm using jade editing mode not only for js templating. Specifically, this example is taken from a template for jade2php.

**Comment by davidrios** [comment]
I think I discovered that when I was making the highlighter, I discovered a lot of quirks/features of the Jade compiler in the process. As for the issue, I'm sorry, I shouldn't be saying what you must do, if the Jade compiler support that syntax the highlighter should support it too. I'll look into it as soon as I can.

**Comment by OnkelTem** [comment]
Just updated, it works!
Thank you.
