### ISSUE TITLE
Equals Sign in Unescaped Attributes

### ISSUE THREAD

**Issue by JustinLivi** [davidrios/jade-tmbundle#43]
The equals character in unescaped attributes breaks subsequent syntax highlighting:

```jade
.test-div( example-attr !="=" ) everything beyond this point will highlight incorrectly
.test-div2
```

Using the equals sign in unescaped attributes is necessary for dynamically setting attributes in underscore templates.

Example:

```jade
script(type='text/template', id='tmpl-results-project')
    a.file(href="#", data-project-id !="<%= _id %>" ) Some test text
    .test-div2
```

Judging by the above examples, Github's syntax highlighting seems to suffer from this same issue

**Comment by JustinLivi** [comment]
Note: a simple workaround is to use &attributes, however, I don't think this nullifies the validity of the original issue

```jade
script(type='text/template', id='tmpl-results-project')
    a.file(href="#")&attributes({ 'data-project-id' : "<%= _id %>" }) Some test text
    .test-div2
```

**Comment by davidrios** [comment]
GitHub actually uses this very same highlighter, hence the same bug.

**Comment by davidrios** [comment]
Upon inspection the bug is unrelated to the equal sign, it's about white spaces between attribute names and assignments. Ex.:

```jade
.test-div( example-attr!="=" ) no white spaces no problem
.test-div( example-attr !="string" ) here "string" have the wrong highlighting
.test-div( example-attr!="string" ) this is correct
```

Nevertheless, I'll submit a fix as soon as I can.
