### ISSUE TITLE
Highlighting for dot block text

### ISSUE THREAD

**Issue by igl** [davidrios/jade-tmbundle#44]
![subjade](https://cloud.githubusercontent.com/assets/293519/7497896/8099a67e-f41d-11e4-9937-6132a009085e.png)

Rather pink.

Sublime 3 dev build 3085

**Comment by davidrios** [comment]
I can't reproduce that issue, the same code highlights correctly for me. Can you test with a new file in which that is the only code? If the problem persists, try to uninstall the Jade bundle and reinstalling it manually from github.

**Comment by igl** [comment]
I tried.
![sj-cloned](https://cloud.githubusercontent.com/assets/293519/7516059/b9b18de6-f4cc-11e4-9f05-1a40376dadea.png)
Later I will try to downgrade sublime and also test on linux at home.

**Comment by davidrios** [comment]
see #47
