### ISSUE TITLE
Comments over-highlighting

### ISSUE THREAD

**Issue by partap** [davidrios/jade-tmbundle#45]
Just noticed this in the latest Sublime 3 dev build 3085, but not sure if that's when it started.

![screenshot 2015-05-06 23 48 03](https://cloud.githubusercontent.com/assets/2281220/7509283/e2d822a6-f44b-11e4-97a1-eee4610424e1.png)

If I comment out any line, all following lines are highlighted as comments until there is a line that starts in column 1.

**Comment by geekdada** [comment]
+1

**Comment by samumist** [comment]
+1

**Comment by davidrios** [comment]
see #47
