### ISSUE TITLE
IDs are not highlighted [Sublime Text 3]

### ISSUE THREAD

**Issue by tsurantino** [davidrios/jade-tmbundle#48]
Hi,

I am using ST3 and am finding that whenever I write an ID div i.e. `#mydiv` I am not having it highlighted as I would when I write a class i.e. `.mydiv`.

Is this an issue with my installation or a general bug?

**Comment by onerkript** [comment]
I'm having the same problem with ST2, my IDs aren't highlighted.

**Comment by davidrios** [comment]
@tsurantino which version of st3 are you using?
@onerkript are you using which color theme?

**Comment by tsurantino** [comment]
@davidrios I am using Build 3083. Is it outdated?

**Comment by onerkript** [comment]
@davidrios I was using Flatlant Monokai. I switched to Flatland Dark and now the ID's are highlighted.

**Comment by davidrios** [comment]
@tsurantino your version is correct, might be a problem with your installation or your color theme has differing colors for both. try to change the color theme and see if that solves the problem.

**Comment by davidrios** [comment]
Closing as this doesn't seem to be a bug.
