### ISSUE TITLE
Incorrect javascript highlighting

### ISSUE THREAD

**Issue by mickvangelderen** [davidrios/jade-tmbundle#52]
Hey there, 

I think the following code is incorrectly highlighted:

```js
(function(){
})('=');
```

![Highlighed code](https://cloud.githubusercontent.com/assets/5444990/9561895/49fb8cee-4e5a-11e5-8d78-2c6d7306e054.png)

**Comment by davidrios** [comment]
It works for me. Here too:
```jade
script.
  (function(){
  })('=');
```

Maybe you are using a newer unsupported version of sublime? See #47.

**Comment by mickvangelderen** [comment]
I get this result on Windows 7, Sublime Text 3 build 3083.

**Comment by davidrios** [comment]
Try to disable every custom package installed except this Jade bundle, and see if that have any effect.

**Comment by davidrios** [comment]
I'm closing this for lack of further feedback.
