### ISSUE TITLE
Syntax highlight breaks after include 

### ISSUE THREAD

**Issue by pixelass** [davidrios/jade-tmbundle#55]
This happens when an include is inside a `style` or `script` tag

<img width="391" alt="screen shot 2015-10-11 at 6 30 29 am" src="https://cloud.githubusercontent.com/assets/1148334/10417005/652bee38-6fe2-11e5-9050-28f59f8fb5dd.png">

Sublime Text 3

**Comment by davidrios** [comment]
This happens because in old versions of Jade a style tag not ending with a dot was allowed which rendered CSS inside, and my highlighter followed that. I need to drop that support in order to fix this, but I guess that won't affect a lot of people these days, so it's okay.

**Comment by pixelass** [comment]
and I thought I knew everything about Jade.. Thanks :smile:
