### ISSUE TITLE
[jade] Incorrect highlighting in strings with inline tags

### ISSUE THREAD

**Issue by aeschli** [davidrios/jade-tmbundle#67]
**VS Code version**:
0.10.6 - Using https://github.com/davidrios/jade-tmbundle Jade.tmLanguage version from Oct 26, 2015, but I see the same problem with latest version from Dec 1, 2015

**Code**:
```jade
p #[code samp] — Regular text. #[samp This is sample text] more text.
```

**Description**:
If you try to write a dot in a inline tag (tag Interpolation), text highlighting changes.

**Gif:**
![2016-01-04_15-44-32](https://cloud.githubusercontent.com/assets/7034281/12089842/1cc9f378-b2fa-11e5-8645-2928e9938e16.gif)

_Copied from original issue: Microsoft/vscode#1765_

**Comment by davidrios** [comment]
I tested here and it works correctly using sublime text 2 and 3. In your example it seems to be wrong even before the dot, the text inside the inline tag should also be white, I guess it's more likely a problem on your side.
