### ISSUE TITLE
incorrect highlighting of attributes passing syntax ? 

### ISSUE THREAD

**Issue by sinsunsan** [davidrios/jade-tmbundle#69]
I often use this syntax 
````
mixin projectWorkLoad_noendSwitch
  +uiSwitch({
      ngModel: "data.selectEndDate",
      name: "selectMode",
    })(ng-required: "true")
````
and 
````
mixin uiSwitch(data)
   div(class="text", ngModel=data.ngModel, name=data.name)&attributes(attributes)
````
The syntax is not correctly highlighted for (ng-required: "true") which end white

Do I need a version update ? 
Do you handle this case ? 

Thanks

**Comment by davidrios** [comment]
Testing here it seems to be working correctly. What version of sublime are you using?

**Comment by sinsunsan** [comment]
Sublime 2 / Should I use v3 for this to work ?

**Comment by davidrios** [comment]
I tested with sublime 2 here and got no problems. Do you have the latest version of this highlighter? Also, what color scheme are you using?

**Comment by davidrios** [comment]
Closing for lack of feedback and because I was unable to reproduce the problem.
