### ISSUE TITLE
JADE will be renamed as PUG

### ISSUE THREAD

**Issue by rs459** [davidrios/jade-tmbundle#71]
Hi, 

As mentionned [here](https://github.com/pugjs/jade/issues/2184) 'JADE' will be renamed as 'PUG'.

Do you have any plan about the migration/coexistence ?

I have this plugin [bootstrap3-jade-sublime-plugin](https://github.com/rs459/bootstrap3-jade-sublime-plugin) which depend on yours.

Best regards.

**Comment by davidrios** [comment]
I haven't put much thought into it, but I guess I'll just fork this repo and replace jade for pug there.

**Comment by ilyakam** [comment]
In the meantime, here are the instructions to make sure your syntax highlighter continues to work with `*.pug` files:

1. Preferences » Browse Packages
1. Open `User` folder
1. Edit `Jade.sublime-settings` with the following contents:  
  
  ```json
  {
    "extensions":
    [
      "pug"
    ]
  }
  ```

4. Restart SublimeText

**Comment by equinusocio** [comment]
https://github.com/davidrios/jade-tmbundle/pull/75

**Comment by davidrios** [comment]
I've created a new package for Pug, check it out: https://github.com/davidrios/pug-tmbundle
