### ISSUE TITLE
Jade files are modified by the plugin periodically without any actions

### ISSUE THREAD

**Issue by name-k** [davidrios/jade-tmbundle#72]
I'm using latest sublime text 3 and gulp.js as a tool to build projects.

When I enable Jade plugin in ST3, it modifies jade files every couple of seconds and that triggers gulp watcher every time files are modified. I am not really strong at debugging such problems but I found out that disabling Jade package in ST3 solves the problem, but, obviously is not the right choice.

**Comment by name-k** [comment]
I should mention that the problem is only with .jade files and only if I use ST3 with Jade package enabled. All other filetypes are not touched.

If you want to reproduce the problem, you can use my project template https://github.com/name-k/frontend-template

**Comment by name-k** [comment]
Just checked on my Mac, everything is ok. So the problem is related only to Windows (Win 10 in my case).

**Comment by davidrios** [comment]
Have you tried with a fresh install of sublime and only this package installed?

**Comment by name-k** [comment]
No, I did not and, unfortunatelly, my PC laptop stopped to charge today. I'll do it when I'll fix it.

**Comment by name-k** [comment]
I checked on clean Windows 10 installation, only Jade plugin was installed in ST3 and turned out the problem is not just in Jade plugin itself. 
I've started to install different packages one-by-one, and found out that it is the combination of Jade and Git plugins. If two of them enabled - the bug happens. If one of the plugins is disabled - everything goes fine.

**Comment by davidrios** [comment]
Closing because it's not a problem with this package.
