### ISSUE TITLE
[jade] comment line color wronly colored after new lines

### ISSUE THREAD

**Issue by aeschli** [davidrios/jade-tmbundle#74]
_From @Lonefy on March 16, 2016 2:50_

- VSCode Version: 0.10.11
- OS Version: win10

the color of first comment line seems incorrect,when there are `odd number of empty line` before.
screen shot:
![image](https://cloud.githubusercontent.com/assets/7921431/13800349/77c243ec-eb63-11e5-8e83-9a7254940e4f.png)

![image](https://cloud.githubusercontent.com/assets/7921431/13800477/9a150d84-eb64-11e5-84a3-41e0dd85a3a7.png)

![image](https://cloud.githubusercontent.com/assets/7921431/13800363/8db9cefe-eb63-11e5-9360-07479191ba4c.png)

_Copied from original issue: Microsoft/vscode#4287_

**Comment by aeschli** [comment]
Reproduced with snippet
```
.ssdsd
	ul.asdasd
		li.asdasd
	
	// asdsdas
```

**Comment by phoenixenero** [comment]
This issue exists (coding in VS Code), why did you close this?

**Comment by phoenixenero** [comment]
Here's the video

https://dl.dropboxusercontent.com/u/105405645/video/2016-04-04-1613-08.flv

**Comment by phoenixenero** [comment]
Here's a video showing the problem in action:

https://dl.dropboxusercontent.com/u/105405645/video/jade-tmbundle.mp4

**Comment by davidrios** [comment]
I understand, this issue does exist, but only on VSCode, so it is invalid in the context of this package.

**Comment by phoenixenero** [comment]
Ah ok.
