### ISSUE TITLE
Incorrect highlighting for a tag starting with # and ending at the dot

### ISSUE THREAD

**Issue by mrmlnc** [davidrios/jade-tmbundle#84]
Minimal code example that is causing the problem:

```jade
#test(abc="asdfsdf").
	another case of text block
```

Demo:
![2016-09-10_01-06-35](https://cloud.githubusercontent.com/assets/7034281/18404418/05a35fc8-76f3-11e6-82bd-33dd59daf330.gif)

I conducted a "study" and concluded that it related to: [dot_block_tag.py](https://github.com/davidrios/jade-tmbundle/blob/master/Syntaxes/dot_block_tag.py).

**Comment by davidrios** [comment]
That is only happening on your custom version of this highlighter right? That's because you didn't change the scope name for classes and ids in all places. I did that too with 46cdd23cd68c18a50cf6044447e116223d05775b.

**Comment by mrmlnc** [comment]
@davidrios, thanks for you review. I don't fully understand this big RegExp.
