### ISSUE TITLE
Hang when opening specific file (Sublime 3, build 3124)

### ISSUE THREAD

**Issue by bramus** [davidrios/jade-tmbundle#85]
I've noticed that with the most recent build of Sublime Text 3 (build 3124) on macOS Sierra 10.12 the syntax highlighting of `.jade` files has become slower. Mainly files that contain `script.` blocks seem to be slower to me.

One file that even totally hangs Sublime is https://gist.github.com/bramus/32e4e5ff9ec3c43669db8a4d490cb231

Disabling the Jade bundle through Package Control no long crashes Sublime.

Perhaps this is linked to #47?

**Comment by davidrios** [comment]
No relation with #47. It's a problem with build 3124, it's shipping a new built-in JavaScript highlighter that have some issues with this bundle. Try to revert to the previous stable release and see if the problem persists. Or install the Babel bundle and restart sublime and check if the problem is solved.

**Comment by davidrios** [comment]
Actually the problem exists since build 3114, try build 3103.

**Comment by davidrios** [comment]
If installing Babel, disable internal JavaScript package:

Preferences > ignored_packages > ["Vintage", "JavaScript"]

**Comment by bramus** [comment]
Thanks for looking into this @davidrios, disabling the `JavaScript` and `Vintage` indeed did the trick (`Babel` was already installed).

**Comment by JohnKulp** [comment]
I've been having the same problem on OS X El Capitan 10.11.6.  Whenever I attempted to open a jade file, sublime would entirely crash during loading.  I installed an alternative javascript package as a workaround, but it would be wonderful to see this issue fixed.

**Comment by davidrios** [comment]
Have you guys tried the latest stable build 3126? I tested here and it seems to have resolved the issue.

**Comment by bramus** [comment]
Build 3126 indeed fixes this issue. Thanks!
